name: "Preview environment regression check"
on:
    workflow_run:
        workflows: ["Build"]
        types: [completed]
        branches: ["main"]
    workflow_dispatch:
        inputs:
            name:
                required: true
                description: "The name of the preview environment"
            version:
                required: true
                description: "The version of Gitpod to install"
            infrastructure_provider:
                description: "The infrastructure provider to use. Valid options: harvester, gcp"
                required: false
                default: harvester
jobs:
    # TODO: Add configuration job here like we have in build
    # Also see here https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow
    # for how to get data from the triggering workflow (we need that to get the version)
    check:
        name: Check for regressions
        # TODO: This should use config output instead and it should work for dispatch events too.
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: [self-hosted]
        steps:
            - uses: actions/checkout@v3
            - name: Create preview environment infrastructure
              uses: ./.github/actions/preview-create
              with:
                  name: ${{ github.event.inputs.name }}
                  infrastructure_provider: ${{ github.event.inputs.infrastructure_provider }}
                  sa_key: ${{ secrets.GCP_CREDENTIALS }}
            - name: Deploy Gitpod to the preview environment
              id: deploy-gitpod
              uses: ./.github/actions/deploy-gitpod
              with:
                  name: ${{ github.event.inputs.name }}
                  sa_key: ${{ secrets.GCP_CREDENTIALS }}
                  version: ${{ github.event.inputs.version}}
            - name: Check
              run: |
                  echo "No regressions caught because I didn't check anything 🤡 Sleeping for 2 minutes."
                  sleep 60
            - name: Delete preview environment
              if: always()
              uses: ./.github/actions/delete-preview
              with:
                  name: ${{ github.event.inputs.name }}
                  sa_key: ${{ secrets.GCP_CREDENTIALS }}
